#pragma once

#include "otto/base.h"
#include "otto/platform_detection.h"

#include "otto/util/map.h"
#include "otto/util/pair.h"
#include "otto/util/file.h"
#include "otto/util/result.h"
#include "otto/util/shared.h"
#include "otto/util/string.h"
#include "otto/util/triple.h"
#include "otto/util/unique.h"
#include "otto/util/function.h"
#include "otto/util/optional.h"
#include "otto/util/file_path.h"
#include "otto/util/file_utils.h"
#include "otto/util/static_array.h"
#include "otto/util/dynamic_array.h"

#include "otto/math/math.h"
#include "otto/math/vec2.h"
#include "otto/math/vec3.h"
#include "otto/math/vec4.h"
#include "otto/math/mat2x2.h"
#include "otto/math/mat3x3.h"
#include "otto/math/mat4x4.h"

#include "otto/debug/log.h"
#include "otto/debug/profiler.h"

#include "otto/core/time.h"
#include "otto/core/application.h"
#include "otto/core/application_events.h"

#include "otto/scene/view.h"
#include "otto/scene/scene.h"
#include "otto/scene/entity.h"
#include "otto/scene/system.h"
#include "otto/scene/behaviour.h"
#include "otto/scene/multi_view.h"
#include "otto/scene/serialization.h"
#include "otto/scene/scene_manager.h"
#include "otto/scene/component_pool.h"

#include "otto/serialization/serialized.h"
#include "otto/serialization/serializer.h"
#include "otto/serialization/serialization.h"

#include "otto/window/window.h"
#include "otto/window/window_mode.h"

#include "otto/window/icon/cursor.h"
#include "otto/window/icon/icon.h"

#include "otto/window/input/keys.h"
#include "otto/window/input/mouse.h"
#include "otto/window/input/keyboard.h"
#include "otto/window/input/mouse_buttons.h"

#include "otto/event/event_listener.h"
#include "otto/event/event_dispatcher.h"

#include "otto/graphics/color.h"
#include "otto/graphics/shader.h"
#include "otto/graphics/sprite.h"
#include "otto/graphics/context.h"
#include "otto/graphics/texture_2D.h"
#include "otto/graphics/vertex_array.h"
#include "otto/graphics/graphics_api.h"
#include "otto/graphics/vertex_buffer.h"
